#!/bin/bash

# ==============================================================================
# Generate VEBA Viral Binning Commands
#
# Description:
#   This script generates a list of shell commands to perform viral binning on
#   assembled scaffolds using the VEBA tool. It takes the assembly output
#   (scaffolds and alignment maps) for each sample and identifies potential
#   viral contigs, grouping them into bins.
#
# Dependencies:
#   This script must be run *after* the assembly step is complete. It requires
#   the `scaffolds.fasta` and `mapped.sorted.bam` files generated by the
#   'assembly' script.
#
# Inputs:
#   - ../../identifiers.list: A text file containing one sample ID per line.
#   - Assembled scaffolds: `.../assembly/${id}/output/scaffolds.fasta`
#   - BAM alignment file: `.../assembly/${id}/output/mapped.sorted.bam`
#   - VEBA Database: A reference database required for the binning process.
#
# Outputs:
#   - commands.binning_viral.list: A file containing the full list of commands.
#   - logs/: A directory to store standard output and error logs from each job.
#   - The VEBA tool will write the final viral bins to the `output_directory`.
# ==============================================================================

# --- Configuration ---

# Base path to the locally mounted S3 bucket.
s3_path="/home/ubuntu/jolespin-volume/s3"

# Path to the VEBA reference database required for the binning module.
veba_database="${s3_path}/newatlantis-raw-veba-db-prod/VEBA/VEBA-DB_v9"

# Directory where the final viral binning output will be stored.
# This should be on a shared file system like EFS.
output_directory="../../Analysis/veba_output/binning/viral/"


# --- Script Execution ---

# Ensure the main output directory exists. The logs/ directory should exist from previous steps.
mkdir -p "${output_directory}"

# Clean up any pre-existing command list file to start fresh.
rm -f commands.binning_viral.list
echo "Generating VEBA viral binning commands..."

# Iterate through each sample identifier provided in the list file.
for id in $(cat ../../identifiers.list);
do
        # Create a unique job name for logging purposes.
        job_name="binning-viral__${id}"
        echo "Processing sample: ${id}"

        # Path to the assembled scaffolds from the previous step.
        fasta="../../Analysis/veba_output/assembly/${id}/output/scaffolds.fasta"
        # Path to the sorted BAM file (read alignments) from the previous step.
        bam="../../Analysis/veba_output/assembly/${id}/output/mapped.sorted.bam"

        # Assemble the parameters string for the VEBA binning-viral module.
        # -f: input scaffolds FASTA
        # -b: input BAM file for coverage information
        # -n: sample name/ID
        # -o: output directory
        # -p: number of processors/threads
        # -m: minimum contig length to consider (1500 bp)
        params="-f ${fasta} -b ${bam} -n ${id} -o ${output_directory} -p=8 -m 1500 --veba_database ${veba_database}"

        # Construct the full command to run the VEBA binning module.
        cmd="/usr/bin/time -v veba --module binning-viral --params='${params}'"

        # Append the complete command, with output/error redirection, to the list file.
        echo "${cmd} 2> logs/${job_name}.e 1> logs/${job_name}.o" >> commands.binning_viral.list

done

echo "Command generation complete. See 'commands.binning_viral.list'."
