#!/bin/bash

# ==============================================================================
# Generate VEBA Assembly Commands
#
# Description:
#   This script generates a list of shell commands to assemble preprocessed
#   sequencing reads using the VEBA tool. It reads a list of sample
#   identifiers and uses the trimmed FASTQ files generated by the
#   'preprocess' script as input for the assembly.
#
# Dependencies:
#   This script must be run *after* the preprocessing step is complete, as it
#   relies on the trimmed FASTQ files located in the preprocess output directory.
#
# Inputs:
#   - ../../identifiers.list: A text file containing one sample ID per line.
#   - Trimmed FASTQ files from the preprocessing step, located at:
#     `../../Analysis/veba_output/preprocess/${id}/output/trimmed_*.fastq.gz`
#
# Outputs:
#   - commands.assembly.list: A file containing the full list of commands
#     that can be run to perform the assembly.
#   - logs/: A directory to store standard output and error logs from each job.
#   - The VEBA tool will write the final assemblies to the `output_directory`.
# ==============================================================================

# --- Configuration ---

# Directory where the final assembly output from VEBA will be stored.
# This should be on a shared file system like EFS.
output_directory="../../Analysis/veba_output/assembly/"


# --- Script Execution ---

# Ensure the main output and log directories exist.
mkdir -p "${output_directory}"
mkdir -p "logs/"

# Clean up any pre-existing command list file to start fresh.
rm -f commands.assembly.list
echo "Generating VEBA assembly commands..."

# Iterate through each sample identifier provided in the list file.
for id in $(cat ../../identifiers.list);
do
        # Create a unique job name for logging purposes.
        job_name="assembly__${id}"
        echo "Processing sample: ${id}"

        # Define the paths to the preprocessed (trimmed) FASTQ files.
        r1="../../Analysis/veba_output/preprocess/${id}/output/trimmed_1.fastq.gz"
        r2="../../Analysis/veba_output/preprocess/${id}/output/trimmed_2.fastq.gz"

        # Assemble the parameters string for the VEBA assembly module.
        params="-1 ${r1} -2 ${r2} -n ${id} -o ${output_directory} -p=8"

        # Construct the full command to run the VEBA assembly module.
        # Note: You can customize the assembler by uncommenting and adding flags like:
        # --program megahit --megahit_preset meta-large
        cmd="/usr/bin/time -v veba --module assembly --params='${params}'"

        # Append the complete command, with output and error redirection, to the list file.
        echo "${cmd} 2> logs/${job_name}.e 1> logs/${job_name}.o" >> commands.assembly.list

done

echo "Command generation complete. See 'commands.assembly.list'."
